name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:    

jobs:
  run-tests:
    runs-on: ubuntu-latest 

    #matriz para ejecutar a la vez los 3 test.sh
    strategy:
      matrix:
        script: [test1.sh, test2.sh, test3.sh]
    steps:
      - name: Check out code
        uses: actions/checkout@v2

     # - name: Set execute permissions for test scripts
     #   run: chmod +x ${{ matrix.script }}

      - name: Run the test
        run: ./${{ matrix.script }}
